#!/usr/bin/env bash
# Generates .env.production with a random Postgres password (used both to
# start the postgres container and inside DATABASE_URL, kept in sync here so
# there's no risk of hand-editing one and forgetting the other). Run once,
# before the first `deploy/up.sh`.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env.production ]; then
  echo ".env.production already exists - refusing to overwrite it." >&2
  echo "Delete it first if you really want to regenerate (this rotates the DB password)." >&2
  exit 1
fi

PG_PASSWORD=$(openssl rand -hex 24)

cat > .env.production <<EOF
# Generated by deploy/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Keep this file out of git (it's already in .gitignore) and back it up
# somewhere safe - it's the only copy of the DB password.

POSTGRES_USER=postgres
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=calendariodocenti
DATABASE_URL=postgresql://postgres:${PG_PASSWORD}@postgres:5432/calendariodocenti

API_TITLE=Calendario Docenti API
API_VERSION=0.1.0
DEBUG=False
SOLVER_TIMEOUT_SECONDS=60
USE_S3=False
TEMP_DIR=/tmp/calendariodocenti

# Optional: only needed for the AI chat copilot (app/services/chat.py).
# Leave empty to keep that feature disabled - everything else works without
# it. Get a key at https://console.anthropic.com - usage-based billing, not
# covered by any of the zero-cost hosting choices.
ANTHROPIC_API_KEY=

# The domain Caddy will request a Let's Encrypt certificate for - see
# deploy/Caddyfile. Must already point (DNS A record) at this machine's
# public IP before first start, or Caddy's ACME challenge will fail.
DOMAIN=orario.tuodominio.it
EOF

chmod 600 .env.production
echo "Wrote .env.production (DB password generated, DOMAIN left as a placeholder - edit it before deploying)."
