/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DatiRouteImport } from './routes/dati'
import { Route as DisponibilitaRouteImport } from './routes/disponibilita'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrarioRouteImport } from './routes/orario'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DatiIndexRouteImport } from './routes/dati.index'
import { Route as DatiAccoppiamentiRouteImport } from './routes/dati.accoppiamenti'
import { Route as DatiAssegnazioniRouteImport } from './routes/dati.assegnazioni'
import { Route as DatiCalendarioRouteImport } from './routes/dati.calendario'
import { Route as DatiClassiRouteImport } from './routes/dati.classi'
import { Route as DatiDocentiRouteImport } from './routes/dati.docenti'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DatiRoute = DatiRouteImport.update({
  id: '/dati',
  path: '/dati',
  getParentRoute: () => rootRouteImport,
} as any)
const DisponibilitaRoute = DisponibilitaRouteImport.update({
  id: '/disponibilita',
  path: '/disponibilita',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrarioRoute = OrarioRouteImport.update({
  id: '/orario',
  path: '/orario',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DatiIndexRoute = DatiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DatiRoute,
} as any)
const DatiAccoppiamentiRoute = DatiAccoppiamentiRouteImport.update({
  id: '/accoppiamenti',
  path: '/accoppiamenti',
  getParentRoute: () => DatiRoute,
} as any)
const DatiAssegnazioniRoute = DatiAssegnazioniRouteImport.update({
  id: '/assegnazioni',
  path: '/assegnazioni',
  getParentRoute: () => DatiRoute,
} as any)
const DatiCalendarioRoute = DatiCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => DatiRoute,
} as any)
const DatiClassiRoute = DatiClassiRouteImport.update({
  id: '/classi',
  path: '/classi',
  getParentRoute: () => DatiRoute,
} as any)
const DatiDocentiRoute = DatiDocentiRouteImport.update({
  id: '/docenti',
  path: '/docenti',
  getParentRoute: () => DatiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dati': typeof DatiRouteWithChildren
  '/disponibilita': typeof DisponibilitaRoute
  '/menu': typeof MenuRoute
  '/orario': typeof OrarioRoute
  '/setup': typeof SetupRoute
  '/dati/accoppiamenti': typeof DatiAccoppiamentiRoute
  '/dati/assegnazioni': typeof DatiAssegnazioniRoute
  '/dati/calendario': typeof DatiCalendarioRoute
  '/dati/classi': typeof DatiClassiRoute
  '/dati/docenti': typeof DatiDocentiRoute
  '/dati/': typeof DatiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/disponibilita': typeof DisponibilitaRoute
  '/menu': typeof MenuRoute
  '/orario': typeof OrarioRoute
  '/setup': typeof SetupRoute
  '/dati/accoppiamenti': typeof DatiAccoppiamentiRoute
  '/dati/assegnazioni': typeof DatiAssegnazioniRoute
  '/dati/calendario': typeof DatiCalendarioRoute
  '/dati/classi': typeof DatiClassiRoute
  '/dati/docenti': typeof DatiDocentiRoute
  '/dati': typeof DatiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dati': typeof DatiRouteWithChildren
  '/disponibilita': typeof DisponibilitaRoute
  '/menu': typeof MenuRoute
  '/orario': typeof OrarioRoute
  '/setup': typeof SetupRoute
  '/dati/accoppiamenti': typeof DatiAccoppiamentiRoute
  '/dati/assegnazioni': typeof DatiAssegnazioniRoute
  '/dati/calendario': typeof DatiCalendarioRoute
  '/dati/classi': typeof DatiClassiRoute
  '/dati/docenti': typeof DatiDocentiRoute
  '/dati/': typeof DatiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dati'
    | '/disponibilita'
    | '/menu'
    | '/orario'
    | '/setup'
    | '/dati/accoppiamenti'
    | '/dati/assegnazioni'
    | '/dati/calendario'
    | '/dati/classi'
    | '/dati/docenti'
    | '/dati/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/disponibilita'
    | '/menu'
    | '/orario'
    | '/setup'
    | '/dati/accoppiamenti'
    | '/dati/assegnazioni'
    | '/dati/calendario'
    | '/dati/classi'
    | '/dati/docenti'
    | '/dati'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dati'
    | '/disponibilita'
    | '/menu'
    | '/orario'
    | '/setup'
    | '/dati/accoppiamenti'
    | '/dati/assegnazioni'
    | '/dati/calendario'
    | '/dati/classi'
    | '/dati/docenti'
    | '/dati/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DatiRoute: typeof DatiRouteWithChildren
  DisponibilitaRoute: typeof DisponibilitaRoute
  MenuRoute: typeof MenuRoute
  OrarioRoute: typeof OrarioRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dati': {
      id: '/dati'
      path: '/dati'
      fullPath: '/dati'
      preLoaderRoute: typeof DatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disponibilita': {
      id: '/disponibilita'
      path: '/disponibilita'
      fullPath: '/disponibilita'
      preLoaderRoute: typeof DisponibilitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orario': {
      id: '/orario'
      path: '/orario'
      fullPath: '/orario'
      preLoaderRoute: typeof OrarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dati/': {
      id: '/dati/'
      path: '/'
      fullPath: '/dati/'
      preLoaderRoute: typeof DatiIndexRouteImport
      parentRoute: typeof DatiRoute
    }
    '/dati/accoppiamenti': {
      id: '/dati/accoppiamenti'
      path: '/accoppiamenti'
      fullPath: '/dati/accoppiamenti'
      preLoaderRoute: typeof DatiAccoppiamentiRouteImport
      parentRoute: typeof DatiRoute
    }
    '/dati/assegnazioni': {
      id: '/dati/assegnazioni'
      path: '/assegnazioni'
      fullPath: '/dati/assegnazioni'
      preLoaderRoute: typeof DatiAssegnazioniRouteImport
      parentRoute: typeof DatiRoute
    }
    '/dati/calendario': {
      id: '/dati/calendario'
      path: '/calendario'
      fullPath: '/dati/calendario'
      preLoaderRoute: typeof DatiCalendarioRouteImport
      parentRoute: typeof DatiRoute
    }
    '/dati/classi': {
      id: '/dati/classi'
      path: '/classi'
      fullPath: '/dati/classi'
      preLoaderRoute: typeof DatiClassiRouteImport
      parentRoute: typeof DatiRoute
    }
    '/dati/docenti': {
      id: '/dati/docenti'
      path: '/docenti'
      fullPath: '/dati/docenti'
      preLoaderRoute: typeof DatiDocentiRouteImport
      parentRoute: typeof DatiRoute
    }
  }
}

interface DatiRouteChildren {
  DatiAccoppiamentiRoute: typeof DatiAccoppiamentiRoute
  DatiAssegnazioniRoute: typeof DatiAssegnazioniRoute
  DatiCalendarioRoute: typeof DatiCalendarioRoute
  DatiClassiRoute: typeof DatiClassiRoute
  DatiDocentiRoute: typeof DatiDocentiRoute
  DatiIndexRoute: typeof DatiIndexRoute
}

const DatiRouteChildren: DatiRouteChildren = {
  DatiAccoppiamentiRoute: DatiAccoppiamentiRoute,
  DatiAssegnazioniRoute: DatiAssegnazioniRoute,
  DatiCalendarioRoute: DatiCalendarioRoute,
  DatiClassiRoute: DatiClassiRoute,
  DatiDocentiRoute: DatiDocentiRoute,
  DatiIndexRoute: DatiIndexRoute,
}

const DatiRouteWithChildren = DatiRoute._addFileChildren(DatiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DatiRoute: DatiRouteWithChildren,
  DisponibilitaRoute: DisponibilitaRoute,
  MenuRoute: MenuRoute,
  OrarioRoute: OrarioRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
